"""Thai audio clips (spec §16.3).

  python scripts/gen_audio_script.py          # writes scripts/audio_script.md (what to record)
  python scripts/gen_audio_script.py --scan   # after recording: writes app/public/audio/th/manifest.json
                                              # listing only clip files that actually exist

Clip ids and texts are read from app/src/config/thai_templates.ts and aspects.ts so the
script never drifts from the app. Recordings must be made by a Thai speaker [MANUAL];
do not substitute synthetic TTS output.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CFG = ROOT / "app" / "src" / "config"
AUDIO = ROOT / "app" / "public" / "audio" / "th"
EXTS = (".mp3", ".m4a")

THAI_NUM = ["", "หนึ่ง", "สอง", "สาม", "สี่", "ห้า", "หก", "เจ็ด", "แปด", "เก้า"]


def thai_number(n: int) -> str:
    if n == 10:
        return "สิบ"
    tens, ones = divmod(n, 10)
    t = "" if tens == 0 else ("สิบ" if tens == 1 else ("ยี่สิบ" if tens == 2 else THAI_NUM[tens] + "สิบ"))
    o = "" if ones == 0 else ("เอ็ด" if ones == 1 and tens > 0 else THAI_NUM[ones])
    return t + o


def clips():
    tpl = (CFG / "thai_templates.ts").read_text()
    block = re.search(r"export const FRAGMENTS = \{(.*?)\} as const", tpl, re.S).group(1)
    frags = re.findall(r"(\w+): '([^']*)'", block)
    max_num = int(re.search(r"MAX_NUMBER_CLIP = (\d+)", tpl).group(1))
    asp = (CFG / "aspects.ts").read_text()
    info = re.search(r"ASPECT_INFO: Record<Aspect, AspectInfo> = \{(.*?)\n\};", asp, re.S).group(1)
    aspects = re.findall(r"(\w+): \{ th: '([^']*)'", info)
    out = [(f"frag_{k}", v, "template fragment") for k, v in frags]
    out += [(f"aspect_{k}", v, "aspect name") for k, v in aspects]
    out += [(f"num_{n}", thai_number(n), f"number {n}") for n in range(1, max_num + 1)]
    return out


def main():
    cs = clips()
    if "--scan" in sys.argv:
        found = {}
        for cid, _, _ in cs:
            for ext in EXTS:
                if (AUDIO / f"{cid}{ext}").exists():
                    found[cid] = f"{cid}{ext}"
                    break
        AUDIO.mkdir(parents=True, exist_ok=True)
        (AUDIO / "manifest.json").write_text(json.dumps({"clips": found}, ensure_ascii=False, indent=1))
        total = sum((AUDIO / f).stat().st_size for f in found.values())
        print(f"{len(found)}/{len(cs)} clips found, {total / 1024 / 1024:.2f} MB → manifest.json")
        missing = [c for c, _, _ in cs if c not in found]
        if missing:
            print("missing (those sentences fall back to speechSynthesis):", ", ".join(missing))
        return
    L = ["# Thai audio recording script [MANUAL]", "",
         "Generated by `scripts/gen_audio_script.py` from the app's template config — re-run it if templates change.", "",
         "**Who:** a native Central Thai speaker (Noor or her daughter is ideal — a familiar voice). "
         "Do **not** use synthetic TTS for these files.", "",
         "**How:** record each line as a separate file, named exactly as in the *file* column, in mono, "
         "mp3 (64–96 kbps) or m4a/AAC. Quiet room, phone ~20 cm from the mouth. Leave ~0.1 s of silence at each end "
         "and speak at a calm, even pace — clips are played back-to-back to make sentences such as "
         "“แขก · 5 · คนชอบ · การชิมกาแฟ”. Keep the intonation neutral (not sentence-final) for fragments that sit mid-sentence.", "",
         f"Put the files in `app/public/audio/th/`, then run `python scripts/gen_audio_script.py --scan` to build the manifest. "
         "Target total < 5 MB (spec §16.3).", "",
         f"{len(cs)} clips:", "", "| # | file | say | kind |", "|---|---|---|---|"]
    for i, (cid, text, kind) in enumerate(cs, 1):
        L.append(f"| {i} | `{cid}.mp3` | {text} | {kind} |")
    L += ["", "Example sentences built from these clips (for a practice read-through):", "",
          "- แขก · 5 · คนชอบ · การชิมกาแฟ", "- แขก · 2 · คนไม่ชอบ · การเดินชมสวน",
          "- แขก · 3 · คนชอบ · 1 · คนไม่ชอบ · เรื่อง · อาหาร", "- มี · 4 · ความเห็นที่ระบบไม่แน่ใจ ให้คนช่วยดู"]
    (ROOT / "scripts" / "audio_script.md").write_text("\n".join(L) + "\n")
    print(f"wrote scripts/audio_script.md ({len(cs)} clips)")


if __name__ == "__main__":
    main()
